### ISSUE TITLE
Incomplete Specification for the Processing Method

### ISSUE THREAD

**Issue by TJCoding** [hangong/Xiao06_color_transfer#1]
The processing method described in the paper _“Color Transfer in Correlated Color Space_” [_Ref 1_] is ill-defined. It implies that when the covariance matrices are decomposed using the SVD algorithm, then the eigenvalues along the diagonal of each scaling matrix can be identified by the letters _R G B_ respectively.    This notation is inappropriate because the associated eigenvector matrix defines new axes that are no longer aligned to the original red, green and blue axes.    

By applying the same notation to both the source image matrix and the target image matrix, the paper assumes a correspondence between the two sets of matrices, but this assumption is not justified.    The rotations defined by the source image eignvectors define one set of axes and those defined by the target image eignvectors define another set of axes.  

By convention, the eigenvalues are presented in descending order and the eigenvectors are ordered accordingly.   This often leads to the situation where there is a coincidental correspondence between the ordered axes for the source image and the ordered axes for the target image but this correspondence does not occur for all instances of source image and target image.

The screen shot below shows one instance where the correspondence breaks down for the current Matlab implementation of the Xiao method. 

![Original](https://user-images.githubusercontent.com/62269755/79641275-60f17f00-818e-11ea-8239-cfa40a120b7f.jpg)

Here, in the output image, the grass is coloured purple and the mountain is coloured green when it should be the other way around.  It is interesting to note that the implementation in C++ at [_Ref 2_] does give an image which appears correct.  For certain other image pairs, both implementations give images that are wrong, whereas both implementations give a correct output for the original images utilised in [_Ref 1_] .

In order to ensure that the output image is correct, it is necessary to achieve the best alignment between the axes derived from the source image and those derived from the target image.  This can be achieved by permuting the ordering of one of the sets of axes (say the target axes) and finding the permutation where the vector dot products between the sets of axes have a maximum summation value.  (In practice two axes may be aligned but pointing in the opposite direction, so it is the sum of the absolute values of the dot products that needs to be maximised.)

New code will be proposed which uses a function ‘_MatchColumns_’ to achieve the best alignment between axes as described above.  With this code the output image is as shown below.

![Ruggedised](https://user-images.githubusercontent.com/62269755/79641288-7bc3f380-818e-11ea-9d13-efc2f186bd4c.jpg)

It has been established that the revised code offers correct processing over a wider range of images than the original code.   It is not known whether it achieves an optimal output for all possible input image pairs.  Given that it took 14 years to identify the shortcomings of the original method, it might  take a while to determine the shortfall if any of the revised method.

The images above can be reproduced with the new code by processing images _2.jpg_ and _1.jpg_, with ‘_ruggedisation_’ set ‘_false_’ in the function ‘_cf_Xiao06.m_’ and ‘_ruggedisation_’ set ‘_true_’ respectively.

Ref 1 
Xiao, Xuezhong, and Lizhuang Ma. "_Color Transfer in Correlated Color  Space_."  in Proceedings of the 2006 ACM international conference on virtual reality continuum and its applications, pp. 305-309. ACM, 2006.

Ref 2
_https://github.com/ZZPot/Xiao-transfer_
#     
#    
**Addendum:**

There should be a few more words here about the characteristics of the processing method.

At first sight the _Xiao_ method appears to necessarily be better than the standard _Reinhard_ method.  The _Reinhard_ method achieves a match of the mean and standard deviation values in the _L-alpha-beta_ domain.  The _Xiao_ method produces an output where the mean values, the standard deviations and the cross covariance values of the colour channels in the output image are exactly matched to those of the target colour image.    

However, the situation is not as simple as it seems.  In the first output image shown above, the green channel has a mean value, a standard deviation value and cross correlation values (with the other channels) matching those of the green channel in the target colour image.  The green channel has the right characteristics but it is predominately associated with the wrong part of the picture.  The mountains are shaded green but the green shading should be applied to the grassy plain.   It is no consolation that the green channel has the requisite statistical characteristics if green colouration is applied to the wrong part of the image.

The ruggedisation processing can reduce any gross error but there is still a residual mismatch error in the second output image shown above.   Effectively, the source rotation matrix defines three new orthogonal axes _A, B, C_ which lie at some orientation to the RGB axes.  Likewise, the target rotation matrix defines three new orthogonal axes _A’, B’, C’_ which are at some orientation to the RGB axes.  Normally the orientations of the two sets of derived axes will not be coincident but the processing method implicitly assumes that they are.
    
Pixels in the source image are initially represented by their RGB co-ordinates and are then represented as points relative to the _ABC_ axes.  Scaling is applied and the points occupy new positions in the _ABC_ space.  The modified points are then mapped back to RGB co-ordinates.   This latter remapping is performed on the basis that a point which has co-ordinates _a, b c_ relative to the _ABC_ axes also has co-ordinates _a, b, c_ relative to the _A’B’C’_ axes.   This processing leads to an outcome where the mean values, the standard deviations and the cross covariance values of the colour channels in the output image are exactly matched to those of the target colour image; however this is typically achieved at the expense of a shift in colour.  Pixels which were pure red or pure green or pure blue in the source image are now a shade of red or a shade of green or a shade of blue in the output image.  Conversely pixels which appear as pure red or pure green or pure blue in the output image were originally a shade of red or a shade of green or a shade of blue in the input image. The extent of the colour shift depends upon the extent of misalignment between the _ABC_ axes and the _A’B’C’_ axes. 

A colour shift need not be a problem per se.  If the source image has green grass and the target image has grass which is a different shade of green, then it would be expected that the colour of the grass would have undergone a shift in the final image.  This expectation would apply whether the Xiao or the Reinhard method was used for processing.    The difference for the Xiao method is that a colour match may be achieved in part by moving the position of colours within in the picture whether this is a gross shift or a lesser shift (according to whether ruggedisation is applied or not).
 
The images below compare the output images from three methods of processing. They are respectively _‘Enhanced Reinhard_’ processing [‘_alpha-beta_’ variant, in Ref 3], ‘_Standard Reinhard_’ processing [Ref 4] and ‘_Ruggedised Xiao_’ processing as described here.

![scotland_composite](https://user-images.githubusercontent.com/62269755/79890441-66053700-83f7-11ea-86dc-c6bbab8afad8.jpg)

It can be seen that the third image has different colour characteristics from the others.  The green at the base of the cottage looks more fluorescent, the grass in front has a slight orange tint which doesn’t seem to be present in the palette of the target image.   It could be argued that the first two images better match the look and feel of the colour target image.  Based on these images it is clear that that the _Xiao_ method can produce images which have distinct colour differences to images produced by other methods.  Further study would be required to determine definitively whether the difference is a positive or a negative.

Ref 3
_https://github.com/TJCoding/Enhanced-Image-Colour-Transfer_

Ref 4
_https://github.com/hangong/reinhard_color_transfer_

**Comment by hangong** [comment]
The code hosted in that repository is to provide the consistent implementation with the paper. So, if there are some loopholes in the original design, I won’t fix it. However, you are encouraged to submit the amended MATLAB code with your patch. I’m happy to include it in a separate directory but will make it clear that this is not the original design.

Could be better if you can ensure the code is compatible with Octave — not everyone has a MATLAB licence.

**Comment by hangong** [comment]
Many thanks. Terry. The workaround solution works great. I will close this issue then?

**Comment by TJCoding** [comment]
Hi Han,

Yes please close the issue.  But I am sorry to tell you that there is a
typo in the ReadMe file ....  'differnet'.

Thank you for running with this. There are a number of ways forward from
here which I will probably deal with in a new repository but I am still
trying to work out which might be best.  My 'iterative technique' gives the
same correlation outcome as the ruggedised Xiao method but there is greater
saturation when the data is subsequently limited to range.  However, the
iteration method can be modified perhaps to overcome this....

I think I previously mentioned that I have now suggested the term 'photo
surrealism' for images that look photorealistic in monochrome but not in
colour (which is a property of Adaptive Recolouring).
https://github.com/ycjing/Neural-Style-Transfer-Papers/issues/14   I have
found that an application such as *Ostagram *can give a good result when it
is asked to apply a 'Van Gogh' style to a selfie, but it gives an
unacceptable result when it is given a modern picture of St Paul's
Cathedral and the Thames and then asked to apply a style using a
Canaletto painting of St Paul's.  On that basis, adaptive recolouring can
sometimes give a good result and sometimes not.  By distinguishing Adaptive
Recolouring as  'photo surrealism', it does not necessarily have to meet
the same standards of accuracy as photorealistic processing methods, just
as painterly applications don't work at present for every artist.  (But I
am still working on possible improvements for Adaptive Recolouring.)

Regards

Terry

**Comment by hangong** [comment]
Thanks. The bottomline is that users should have a solid reason to use it. If not for academic publication reasons, professional user comparison experiments are not necessary.
